baseurl = "http://www.lays.pro/"
languageCode = "en-us"
title = "Cyril Lay"
theme = "hugo-strata-theme"
disqusShortname = "Cyril"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Cyril Lay"
	description = "Personal blog about various fields of computer science"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = true

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "Cyril-Yosemite.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "I'm **Cyril Lay**, a software engineer based in Los Angeles, California."
		# The icons will be shown if you enter your username
		twitter = ""
		github = "cyrillay"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "cyril-lay-2017"

		copyright = [
			"&copy; Cyril Lay",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Welcome to Lay's portal !"
		content = "You will find different articles, links and projects about various fields of computer science, especially data science, data engineering and infrastructure."


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "inference-app-screenshot.png"
			thumb = "thumbs/inference-app-screenshot.png"
			title = "[Image classifier](//datascience.lays.pro)"
			description = "Simple React application connected to my inference REST API. Available at http://datascience.lays.pro"

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "! Currently disabled ! Please contact me using the form below for any enquiry."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"404 Sunset Blvd.",
			"Los Angeles, CA 90400",
			"United States"
		]
		phone = "310-404-****"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "cyril@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
