baseURL = "http://www.lays.pro/"
languageCode = "en-us"
title = "Cyril Lay"

#
# Personalization params
#
[params]
    # project specific params
    description = "Machine Learning Engineer - Contractor"
    author_url = "/blog/blog-summary"
    author_name = "Blog"
    project_url = "//github.com/cyrillay"

    # optionally specify where the content is
    mainSections = ["post"]

    # social share links to appear at the end
    socialShare = true
    # Sets specific share to appear on posts (default behavior is to appear)
    socialShareTwitter = true
    socialShareGoogleplus = false
    socialShareFacebook = true
    socialShareReddit = false
    socialShareLinkedin = true
    socialShareStumbleupon = false
    socialSharePinterest = false
    socialShareEmail = true

    # theme's color scheme
    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"


[social]
    # Coding Communities
    github           = "cyrillay"
    # Publishing Communities
    linkedin         = ""
    # Email
    email = "cyril@lays.pro"

# Adjust privacy settings
# See: https://gohugo.io/about/hugo-and-gdpr/

[privacy]
    [privacy.disqus]
      disable = true

    [privacy.googleAnalytics]
      disable = true
      anonymizeIP = true
      respectDoNotTrack = true
      useSessionStorage = true